version: '3'
services:
  itsec1-bot:
    hostname: itsec1-bot
    container_name: itsec1-bot
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./app/:/app/app
    ports:
      - 8080:8080
    restart: always
    networks:
      - net

  langflow:
    build:
      context: ./docker/langflow
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    volumes:
      - ./docker/langflow:/app

  ollama:
    hostname: ollama
    container_name: ollama
    build:
      context: ./docker/ollama
      dockerfile: Dockerfile
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/app
    networks:
      - net

volumes:
  index_data:
    driver: local
  backups:
    driver: local
  postgres-data:
  ollama_data:
    driver: local

networks:
  net:
    driver: bridge