version: '3'
services:
  lecture-bot:
    hostname: lecture-bot
    container_name: lecture-bot
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./app/:/app/app
#    ports:
#      - 8080:8080
    restart: always
    networks:
      - net
      
  nginx:
    image: nginx
    container_name: my-nginx-container
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d  
    ports:
      - "80:80" 
    networks:
      - net

  langflow:
    build:
      context: ./docker/langflow
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    volumes:
      - ./docker/langflow:/app

  ollama:
    hostname: ollama
    container_name: ollama
    build:
      context: ./docker/ollama
      dockerfile: Dockerfile
 #   ports:
 #     - "11434:11434"
    volumes:
      - ollama_data:/app
    networks:
      - net

volumes:
  index_data:
    driver: local
  backups:
    driver: local
  postgres-data:
  ollama_data:
    driver: local

networks:
  net:
    driver: bridge
